services:
  - type: web
    name: django-app
    runtime: python3
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn learninglog.wsgi:application"
    plan: starter
    env:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString

  - type: pserv
    name: postgres-db
    plan: starter
